approval_policy = "on-request"
sandbox_mode = "workspace-write"
web_search = "live"
personality = "pragmatic"
model = "gpt-5.5"
model_reasoning_effort = "high"
approvals_reviewer = "user"

[sandbox_workspace_write]
network_access = true

[features]
hooks = true

[notice]
hide_full_access_warning = true

[projects."/Users/adam/dots"]
trust_level = "trusted"

[projects."/Users/adam/Projects/cc"]
trust_level = "trusted"

[projects."/Users/adam/Gauntlet/openemr"]
trust_level = "trusted"

[projects."/Users/adam/Projects/mightyfine"]
trust_level = "trusted"

[projects."/Users/adam/Desktop"]
trust_level = "trusted"

[projects."/Users/adam/Projects/agentview"]
trust_level = "trusted"

[projects."/Users/adam/dotfiles"]
trust_level = "trusted"

[projects."/Users/adam/Gauntlet/nerdy"]
trust_level = "trusted"

[tui.model_availability_nux]
"gpt-5.5" = 4

[[hooks.PermissionRequest]]
matcher = "Bash|apply_patch|Edit|Write"

[[hooks.PermissionRequest.hooks]]
type = "command"
command = "/Users/adam/.codex/hooks/notify.sh"
timeout = 5

[[hooks.Stop]]

[[hooks.Stop.hooks]]
type = "command"
command = "/Users/adam/.codex/hooks/notify.sh"
timeout = 5

[hooks.state]

[hooks.state."/Users/adam/.codex/config.toml:permission_request:0:0"]
trusted_hash = "sha256:77bade0cd8b8bec17e98ff66021c6c031a77a976605a8dedbf27299eb60c9418"
enabled = true

[hooks.state."/Users/adam/.codex/config.toml:stop:0:0"]
trusted_hash = "sha256:1a7ccdf1880db27d715c984a54db8fbff1a3d019198251cad942c6ddafd7c96d"
enabled = true

[plugins."superpowers@openai-curated"]
enabled = true

[plugins."figma@openai-curated"]
enabled = true

[mcp_servers.linear]
url = "https://mcp.linear.app/mcp"

[mcp_servers.railway]
url = "https://mcp.railway.com"
enabled = false

[mcp_servers.serena]
command = "serena"
args = ["start-mcp-server", "--context=codex", "--project-from-cwd"]
enabled = false
